{% set version = "0.3.7" %}

package:
  name: numpy-indexed
  version: {{ version }}

source:
  fn: {{ version }}.tar.gz
  url: https://github.com/EelcoHoogendoorn/Numpy_arraysetops_EP/archive/{{ version }}.tar.gz
  md5: 97a57293c12ab6bbf8e79acf1aa742f6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  number: 0

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - numpy
    - future

test:
  imports:
    - numpy_indexed

about:
  home: https://github.com/EelcoHoogendoorn/Numpy_arraysetops_EP
  license: LGPL-3.0
  license_file: LICENSE
  summary: Numpy extensions for set and group_by operations on nd-arrays

extra:
  recipe-maintainers:
    - EelcoHoogendoorn
