{% set version = "0.3.5" %}

package:
  name: numpy-indexed
  version: {{ version }}

source:
  fn: {{ version }}.tar.gz
  url: https://github.com/EelcoHoogendoorn/Numpy_arraysetops_EP/archive/{{ version }}.tar.gz
  md5: c751ec1455041bef5bcacafe1a702f7c
  
build:
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .
  number: 1
  
requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - numpy
    - future

test:
  imports:
    - numpy_indexed
  
about:
  home: https://github.com/EelcoHoogendoorn/Numpy_arraysetops_EP
  license: LGPL-3.0
  summary: Numpy extensions for set and group_by operations on nd-arrays

extra:
  recipe-maintainers:
    - EelcoHoogendoorn
